### ISSUE TITLE
Fix bug when turning in current direction

### ISSUE THREAD

**Issue by winkelmannfelix** [winkelmannfelix/Projinda#20]
For example when you turn right when the snake already is moving right the snake will "speed up"

**Comment by winkelmannfelix** [comment]
I think the problem is that when pressing a turning key the program will call the snake_move function instantly, and therefore the snake will move instantly.

**Comment by winkelmannfelix** [comment]
Maybe leave it as it is, can be a fun hidden feature that you can go faster?

**Comment by Oscarerkes** [comment]
I think leave as it is, also raising the skillcap with a feature like this!
